### ISSUE TITLE
Create .NET 6.0 Pluggable Agent Extension

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-engine#2]

**Comment by CharliePoole** [comment]
In fact, no changes to the engine should be needed to do this now. It actually amounts to providing a new extension, a pluggable agent for .NET 6.0. Renaming and keeping this for tracking purposes.

**Comment by jamesehearn** [comment]
Hi! I hate to ask, but I cannot find the information anywhere else. Is there currently an extension for .NET 6.0 support?

**Comment by CharliePoole** [comment]
No.... which is why this issue is still open. :-)

Note the milestone: 2.0. That means there's no plan to provide such an extension, which runs under the TestCentric 1.x. It's a matter not having people available to work on issues.

**Comment by jamesehearn** [comment]
That's what I was thinking, but wanted to make sure I didn't miss some other information somewhere. Will look into what it'd take to resolve this issue. I'd love to contribute in some way. Thanks for building a great tool.

**Comment by CharliePoole** [comment]
Great! Let me know if you have questions.

**Comment by Sputnik24** [comment]
@CharliePoole Hi Charlie, .NET 6 is released almost a year ago. In Alpha 6 of 2.0 version, is still don't see .NET 6 engine. Currently, I'm using issue-823 build. Do I oversee something? Any update on .NET 6 support?

**Comment by CharliePoole** [comment]
Both .NET 6.0 and .NET 7.0 are now available for our tests. I'm assigning this issue and creating a new one for .NET 7.0.

**Comment by jamesehearn** [comment]
I've wanted to work on this so much, but don't really know how to get started. If you *happen* to have suggestions for how to go about this, I'd love to help. Thanks again for all the hard work that you put into this.

**Comment by CharliePoole** [comment]
@jamesehearn If you'd like to work on the engine, you would be welcome. The first step would be to get yourself into a position where you are able to build and test it. Feel free to contact me directly if you run into problems.

**Comment by CharliePoole** [comment]
@YashUoM You're focused on the pluggable agent projects right now, so I'll go ahead and create a new issue for a built-in runner, which can later be the basis for a .NET 6.0 pluggable agent.
